### ISSUE TITLE
Update comments as per suggested in style(9)

### ISSUE THREAD

**Issue by fnoyanisi** [Savagedlight/libifconfig#10]
Hi there,

Not a major one, but I have noticed that some changes have been done based on style(9).

You may want to change 
// comment_here 
style comments to 
/\* comment_here */
as suggested by style(9), which is also ANSI C compliant.

Regards...

**Comment by Savagedlight** [comment]
I won't change this at this time as libifconfig is using xmldoc style comments for documenting the header files (which breaks ANSI C), and because style(9) does not explicitly state it requires single-line comments to be /\* ... */, just that most single-line comments look like that.

**Comment by Savagedlight** [comment]
This will be fixed after the switch from XMLDoc to Javadoc documentation comments.
